/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.siedrig;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author romeu
 */
public class MenuCampus extends javax.swing.JFrame {

    private ArrayList<ArvoreBinariaIt> arvores;
    private int indiceArvoreAtual;
    // layout = new CardLayout()
   // painel que contém lblCampus, treePanel, botões

    private TreePanel treePanel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCampus.class.getName());
    private static final String[] CAMPUS_NOMES = {"São Miguel Paulista", "Anália Franco", "Guarulhos", "Liberdade", "Paulista", "Santo Amaro", "Villa Lobos"};

    private void inicializarArvores() {
    arvores = new ArrayList<>();
    arvores.add(new ArvoreBinariaIt()); // São Miguel Paulista
    arvores.add(new ArvoreBinariaIt()); // Anália Franco
    arvores.add(new ArvoreBinariaIt()); // Guarulhos
    arvores.add(new ArvoreBinariaIt()); // Liberdade
    arvores.add(new ArvoreBinariaIt()); // Paulista
    arvores.add(new ArvoreBinariaIt()); // Santo Amaro
    arvores.add(new ArvoreBinariaIt()); // Villa Lobos
    }

    private ArvoreBinariaIt getArvoreAtual() {
        return arvores.get(indiceArvoreAtual);
    }

    private void setArvoreAtual(int indice) {
        if (indice >= 0 && indice < arvores.size()) {
            indiceArvoreAtual = indice;
            lblCampus.setText("Campus: " + getNomeCampusAtual());
        }
    }

    private String getNomeCampusAtual() {
        return switch (indiceArvoreAtual) {
            case 0 -> "São Miguel Paulista";
            case 1 -> "Anália Franco";
            case 2 -> "Guarulhos";
            case 3 -> "Liberdade";
            case 4 -> "Paulista";
            case 5 -> "Santo Amaro";
            case 6 -> "Villa Lobos";
            default -> "Campus desconhecido";
        };
    }

    /**
     * Creates new form MenuCampus
     */
    public MenuCampus() {
    initComponents();
    // abrir com tamanho maior para evitar componentes sobrepostos
    this.setSize(new Dimension(900, 640));
    this.setMinimumSize(new Dimension(700, 480));
    this.setLocationRelativeTo(null);
    inicializarArvores();
    indiceArvoreAtual = 0;
    pnlPlaceholderFill();
    mostrarCard("MENU"); // Garante que o card inicial seja o menu
    btnSMP.addActionListener(e -> frameCampus(0));
    btnANF.addActionListener(e -> frameCampus(1));
    btnGUA.addActionListener(e -> frameCampus(2));
    btnLIB.addActionListener(e -> frameCampus(3));
    btnVoltar.addActionListener(e -> mostrarCard("MENU"));

    }

    private void mostrarCard(String cardName) {
        if (mainCardPanel == null) {
            return;
        }
        java.awt.LayoutManager lm = mainCardPanel.getLayout();
        if (lm instanceof java.awt.CardLayout cl) {
            cl.show(mainCardPanel, cardName);
        } else {
            System.err.println("mainCardPanel não está usando CardLayout");
        }
    }

    private void pnlPlaceholderFill() {
    treePanel = new TreePanel();
    pnlTreePlaceholder.setLayout(new BorderLayout());
    pnlTreePlaceholder.add(treePanel, BorderLayout.WEST); 
    treePanel.revalidate();
    treePanel.repaint();

        if (mainCardPanel.getLayout() instanceof CardLayout) {
            try {
                mainCardPanel.add(pnlMenu, "MENU");
                mainCardPanel.add(pnlCampus, "CAMPUS_GENERICO"); // Corrigido para usar o painel correto
            } catch (Exception ex) {
            }
        }
    }

    private void frameCampus(int indice) {/*altera o frame usado para outro layout*/
        setArvoreAtual(indice);
        ArvoreBinariaIt arvore = getArvoreAtual();
        String nome = getNomeCampusAtual();

        treePanel.setArvore(arvore);
        lblCampus.setText("Campus: " + nome);
        treePanel.revalidate();
        treePanel.repaint();

        // atualizar lista de nomes do campus mostrado
        updateCampusList();

        CardLayout cl = (CardLayout) (mainCardPanel.getLayout());
        cl.show(mainCardPanel, "CAMPUS_GENERICO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topLabel = new javax.swing.JPanel();
        lblCampus = new javax.swing.JLabel();
        mainCardPanel = new javax.swing.JPanel();
        pnlCampus = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        pnlTreePlaceholder = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnSMP = new javax.swing.JButton();
        btnANF = new javax.swing.JButton();
        btnGUA = new javax.swing.JButton();
        btnLIB = new javax.swing.JButton();
        btnPLT = new javax.swing.JButton();
        btnSAM = new javax.swing.JButton();
        btnVLL = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
    // search field removed

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCampus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCampus.setText("Escolha um campus para alterar:");

        javax.swing.GroupLayout topLabelLayout = new javax.swing.GroupLayout(topLabel);
        topLabel.setLayout(topLabelLayout);
        topLabelLayout.setHorizontalGroup(
            topLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLabelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCampus, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        topLabelLayout.setVerticalGroup(
            topLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCampus, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        getContentPane().add(topLabel, java.awt.BorderLayout.PAGE_START);

        mainCardPanel.setLayout(new java.awt.CardLayout());

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTreePlaceholderLayout = new javax.swing.GroupLayout(pnlTreePlaceholder);
        pnlTreePlaceholder.setLayout(pnlTreePlaceholderLayout);
        pnlTreePlaceholderLayout.setHorizontalGroup(
            pnlTreePlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        pnlTreePlaceholderLayout.setVerticalGroup(
            pnlTreePlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

    // configurar painel do campus: árvore à esquerda, lista centralizada com botão Cadastrar acima
    pnlCampus.setLayout(new java.awt.BorderLayout());
    // manter árvore na esquerda (ocupa espaço menor)
    pnlCampus.add(pnlTreePlaceholder, java.awt.BorderLayout.CENTER);

    // painel central: botão cadastrar (top), lista (center), botão voltar (bottom)
    javax.swing.JPanel centerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
    javax.swing.JPanel topButtonPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    topButtonPanel.add(btnCadastrar);
    centerPanel.add(topButtonPanel, java.awt.BorderLayout.WEST);

    lstCampusNames = new javax.swing.JList<>();
    lstCampusNames.setModel(new javax.swing.DefaultListModel<>());
    spCampusNames = new javax.swing.JScrollPane();
    spCampusNames.setViewportView(lstCampusNames);
    spCampusNames.setPreferredSize(new java.awt.Dimension(220, 320));

    // colocar a lista em um painel centralizado
    javax.swing.JPanel namesPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
    namesPanel.add(spCampusNames);
    centerPanel.add(namesPanel, java.awt.BorderLayout.CENTER);

    javax.swing.JPanel bottomButtonPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    bottomButtonPanel.add(btnVoltar);
    centerPanel.add(bottomButtonPanel, java.awt.BorderLayout.SOUTH);

    centerPanel.setPreferredSize(new java.awt.Dimension(200, 400));
    pnlCampus.add(centerPanel, java.awt.BorderLayout.CENTER);

        // layout simplificado para o painel de menu: botões de ação no topo, campo de busca e resultados, e grid de botões abaixo
        pnlMenu.setLayout(new java.awt.BorderLayout());
        
    btnSMP.setText("São Miguel Paulista");
    btnANF.setText("Anália Franco");
    btnGUA.setText("Guarulhos");
    btnLIB.setText("Liberdade");
    btnPLT.setText("Paulista");
        btnPLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLTActionPerformed(evt);
            }
        });

        btnSAM.setText("Santo Amaro");
        btnSAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAMActionPerformed(evt);
            }
        });

        btnVLL.setText("Villa Lobos");
        btnVLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVLLActionPerformed(evt);
            }
        });

        btnQuickInsert = new javax.swing.JButton();
        btnAddName = new javax.swing.JButton();

        btnQuickInsert.setText("Buscar nome");
        btnQuickInsert.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickInsertActionPerformed(evt);
            }
        });

        // Search UI removed per user's request (search text field and results list were removed)
        btnAddName.setText("Adicionar nome");
        btnAddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNameActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        // search list removed
        // criar painel de adicionar nome (card separado)
        pnlAddName = new javax.swing.JPanel();
        lblAddPrompt = new javax.swing.JLabel();
        txtAddName = new javax.swing.JTextField();

        lblAddPrompt.setText("Digite o nome e pressione Enter:");
        txtAddName.setColumns(20);
        txtAddName.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddNameLayout = new javax.swing.GroupLayout(pnlAddName);
        pnlAddName.setLayout(pnlAddNameLayout);
        pnlAddNameLayout.setHorizontalGroup(
            pnlAddNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlAddNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddPrompt)
                    .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        pnlAddNameLayout.setVerticalGroup(
            pnlAddNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAddPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        // adicionar card ao mainCardPanel
        mainCardPanel.add(pnlAddName, "ADD_NAME");

        // substituir GroupLayout padrão por um layout mais simples para o menu
        pnlMenu.setLayout(new java.awt.BorderLayout());
        javax.swing.JPanel topButtons = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        topButtons.add(btnQuickInsert);
        topButtons.add(btnAddName);
        pnlMenu.add(topButtons, java.awt.BorderLayout.NORTH);

    // search area removed (no center search panel)

        javax.swing.JPanel gridPanel = new javax.swing.JPanel(new java.awt.GridLayout(4, 2, 10, 8));
        gridPanel.add(btnSMP);
        gridPanel.add(btnPLT);
        gridPanel.add(btnANF);
        gridPanel.add(btnSAM);
        gridPanel.add(btnGUA);
        gridPanel.add(btnVLL);
        gridPanel.add(btnLIB);
        gridPanel.add(jButton1);
    pnlMenu.add(gridPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainCardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSMPActionPerformed
    frameCampus(0);
    }//GEN-LAST:event_btnSMPActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = JOptionPane.showInputDialog(this, "Digite o nome para cadastrar:", "Cadastrar", JOptionPane.PLAIN_MESSAGE);
        if (nome != null && !nome.trim().isEmpty()) {
            String nomeTrim = nome.trim();
            int campusIndex = -1;
            for (int i = 0; i < arvores.size(); i++) {
                if (arvores.get(i).Listar(nomeTrim)) {
                    campusIndex = i;
                    break;
                }
            }
            if (campusIndex != -1) {
                String[] campusNomes = {"São Miguel Paulista", "Anália Franco", "Guarulhos", "Liberdade", "Paulista", "Santo Amaro", "Villa Lobos"};
                JOptionPane.showMessageDialog(this, "Nome já cadastrado no campus: " + campusNomes[campusIndex], "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                getArvoreAtual().Cadastrar(nomeTrim);
                treePanel.revalidate();
                treePanel.repaint();
                updateCampusList();
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nome = JOptionPane.showInputDialog(this, "Digite o nome para buscar:", "Buscar", JOptionPane.PLAIN_MESSAGE);
        if (nome != null && !nome.trim().isEmpty()) {
            java.util.List<Integer> locs = searchNameLocations(nome.trim());
            if (locs.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nome não encontrado em nenhum campus.", "Buscar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                StringBuilder sb = new StringBuilder();
                if (locs.size() == 1) {
                    sb.append("Nome encontrado no campus: ").append(CAMPUS_NOMES[locs.get(0)]);
                } else {
                    sb.append("Nome encontrado nos campi: ");
                    for (int i = 0; i < locs.size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(CAMPUS_NOMES[locs.get(i)]);
                    }
                }
                JOptionPane.showMessageDialog(this, sb.toString(), "Buscar", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnANFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnANFActionPerformed
    frameCampus(1);
    }//GEN-LAST:event_btnANFActionPerformed

    private void btnGUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUAActionPerformed
    frameCampus(2);
    }//GEN-LAST:event_btnGUAActionPerformed

    private void btnLIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIBActionPerformed
    frameCampus(3);
    }//GEN-LAST:event_btnLIBActionPerformed

    private void btnPLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLTActionPerformed
        // TODO add your handling code here:
        frameCampus(4);
    }//GEN-LAST:event_btnPLTActionPerformed

    private void btnSAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAMActionPerformed
        // TODO add your handling code here:
        frameCampus(5);
    }//GEN-LAST:event_btnSAMActionPerformed

    private void btnVLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVLLActionPerformed
        // TODO add your handling code here:
        frameCampus(6);
    }//GEN-LAST:event_btnVLLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Executa a busca parcial (case-insensitive) nas árvores.
     * @param query termo de busca
     * @return true se ao menos um resultado foi encontrado
     */
    private boolean performSearch(String query) {
        if (query == null || query.trim().isEmpty()) {
            return false;
        }
        String nomeTrim = query.trim().toLowerCase();
        boolean found = false;
        for (int i = 0; i < arvores.size(); i++) {
            java.util.List<String> nomes = arvores.get(i).emOrdemRecursivo();
            for (String n : nomes) {
                if (n != null && n.toLowerCase().contains(nomeTrim)) {
                    found = true;
                    break;
                }
            }
            if (found) break;
        }
        return found;
    }

    /**
     * Retorna os índices dos campi onde o nome exato (case-insensitive) foi encontrado.
     */
    private java.util.List<Integer> searchNameLocations(String nome) {
        java.util.List<Integer> res = new java.util.ArrayList<>();
        if (nome == null || nome.trim().isEmpty()) return res;
        String nomeTrim = nome.trim();
        for (int i = 0; i < arvores.size(); i++) {
            try {
                if (arvores.get(i).Listar(nomeTrim)) {
                    res.add(i);
                }
            } catch (Exception ex) {
                // ignore individual tree errors
            }
        }
        return res;
    }

    /**
     * Atualiza a JList que mostra os nomes do campus atualmente selecionado.
     */
    private void updateCampusList() {
        if (lstCampusNames == null) return;
        javax.swing.DefaultListModel<String> model = (javax.swing.DefaultListModel<String>) lstCampusNames.getModel();
        model.clear();
        java.util.List<String> nomes = getArvoreAtual().emOrdemRecursivo();
        if (nomes != null) {
            for (String n : nomes) {
                model.addElement(n);
            }
        }
    }

    private void btnQuickInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickInsertActionPerformed
        // Pergunta ao usuário o nome para buscar (search field was removed)
        String query = javax.swing.JOptionPane.showInputDialog(this, "Digite o nome para buscar:", "Buscar", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (query != null) {
            java.util.List<Integer> locs = searchNameLocations(query.trim());
            if (locs.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nome não encontrado em nenhum campus.", "Buscar", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                StringBuilder sb = new StringBuilder();
                if (locs.size() == 1) {
                    sb.append("Nome encontrado no campus: ").append(CAMPUS_NOMES[locs.get(0)]);
                } else {
                    sb.append("Nome encontrado nos campi: ");
                    for (int i = 0; i < locs.size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(CAMPUS_NOMES[locs.get(i)]);
                    }
                }
                javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Buscar", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnQuickInsertActionPerformed

    private void btnAddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNameActionPerformed
        // Abrir diálogo para inserir nome e selecionar campus (substitui o card de adicionar)
        String nome = javax.swing.JOptionPane.showInputDialog(this, "Digite o nome para cadastrar:", "Adicionar nome", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (nome == null) {
            return; // usuário cancelou
        }
        if (nome.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum nome fornecido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nomeTrim = nome.trim();
        String[] campusNomes = {"São Miguel Paulista", "Anália Franco", "Guarulhos", "Liberdade", "Paulista", "Santo Amaro", "Villa Lobos"};
        String opc = (String) javax.swing.JOptionPane.showInputDialog(this, "Escolha o campus:", "Selecionar campus", javax.swing.JOptionPane.PLAIN_MESSAGE, null, campusNomes, campusNomes[0]);
        if (opc == null) {
            return; // cancelou seleção
        }
        int idx = -1;
        for (int i = 0; i < campusNomes.length; i++) if (campusNomes[i].equals(opc)) { idx = i; break; }
        if (idx == -1) return;
        java.util.List<Integer> locs = searchNameLocations(nomeTrim);
        if (!locs.isEmpty()) {
            // já existe em algum(s) campus
            StringBuilder sb = new StringBuilder();
            if (locs.size() == 1) {
                sb.append("Nome já cadastrado no campus: ").append(CAMPUS_NOMES[locs.get(0)]);
            } else {
                sb.append("Nome já cadastrado nos campi: ");
                for (int i = 0; i < locs.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(CAMPUS_NOMES[locs.get(i)]);
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            arvores.get(idx).Cadastrar(nomeTrim);
            javax.swing.JOptionPane.showMessageDialog(this, "Nome inserido em: " + CAMPUS_NOMES[idx], "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (idx == indiceArvoreAtual) {
                treePanel.revalidate();
                treePanel.repaint();
                updateCampusList();
            }
        }
    }//GEN-LAST:event_btnAddNameActionPerformed

    private void txtAddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddNameActionPerformed
        String nome = txtAddName.getText();
        if (nome == null || nome.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum nome fornecido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nomeTrim = nome.trim();
        String[] campusNomes = {"São Miguel Paulista", "Anália Franco", "Guarulhos", "Liberdade", "Paulista", "Santo Amaro", "Villa Lobos"};
        String opc = (String) javax.swing.JOptionPane.showInputDialog(this, "Escolha o campus:", "Selecionar campus", javax.swing.JOptionPane.PLAIN_MESSAGE, null, campusNomes, campusNomes[0]);
        if (opc == null) {
            // usuário cancelou
            return;
        }
        int idx = -1;
        for (int i = 0; i < campusNomes.length; i++) if (campusNomes[i].equals(opc)) { idx = i; break; }
        if (idx == -1) return;
        if (arvores.get(idx).Listar(nomeTrim)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nome já existe no campus selecionado.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            arvores.get(idx).Cadastrar(nomeTrim);
            javax.swing.JOptionPane.showMessageDialog(this, "Nome inserido em: " + campusNomes[idx], "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // voltar para menu
            mostrarCard("MENU");
            txtAddName.setText("");
        }
    }//GEN-LAST:event_txtAddNameActionPerformed

 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCampus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnANF;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnGUA;
    private javax.swing.JButton btnLIB;
    private javax.swing.JButton btnPLT;
    private javax.swing.JButton btnSAM;
    private javax.swing.JButton btnSMP;
    private javax.swing.JButton btnVLL;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JPanel pnlCampus;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTreePlaceholder;
    private javax.swing.JPanel topLabel;
    // list of names in the selected campus (shown in campus view)
    private javax.swing.JList<String> lstCampusNames;
    private javax.swing.JScrollPane spCampusNames;
    private javax.swing.JButton btnQuickInsert;
    private javax.swing.JButton btnAddName;
    private javax.swing.JPanel pnlAddName;
    private javax.swing.JTextField txtAddName;
    private javax.swing.JLabel lblAddPrompt;
    // End of variables declaration//GEN-END:variables
}
