/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.siedrig;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author romeu
 */
public class TreePanel extends javax.swing.JPanel {

    private ArvoreBinariaIt arvore;

    public void setArvore(ArvoreBinariaIt arvore) {
        this.arvore = arvore;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (arvore == null) {
            g.drawString("Nenhuma árvore selecionada", 10, 20);
            return;
        }
        List<String> lista = new ArrayList<>();
        arvore.emOrdem(arvore.raiz, lista);
        int y = 20;
        for (String s : lista) {
            g.drawString(s, 10, y);
            y += 15;
        }
    }

    /**
     * Creates new form TreePanel
     */
    public TreePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
